/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/guy.glb -o src/components/Guy.jsx -k -K -r public 
*/

import React, { useEffect } from 'react'
import { useGLTF, useTexture } from '@react-three/drei'

import * as THREE from "three";

import { useGuyContext } from '../contexts/GuyContext';

export default function Guy(props) {
  const { nodes, materials } = useGLTF('/models/guy.glb')

  const { material, color, animation } = useGuyContext();

  const stylizedTextureProps = useTexture({
    normalMap: "/textures/stylized/Stylized_Bricks_005_normal.png",
    roughnessMap: "/textures/stylized/Stylized_Bricks_005_roughness.png",
    aoMap: "/textures/stylized/Stylized_Bricks_005_ambientOcclusion.png",
  });

  stylizedTextureProps.normalMap.repeat.set(1, 1);
  stylizedTextureProps.roughnessMap.repeat.set(1, 1);
  stylizedTextureProps.aoMap.repeat.set(1, 1);
  stylizedTextureProps.normalMap.wrapS = stylizedTextureProps.normalMap.wrapT = THREE.MirroredRepeatWrapping;
  stylizedTextureProps.roughnessMap.wrapS = stylizedTextureProps.roughnessMap.wrapT = THREE.MirroredRepeatWrapping;
  stylizedTextureProps.aoMap.wrapS = stylizedTextureProps.aoMap.wrapT = THREE.RepeatWrapping;

  const portugueseTextureProps = useTexture({
    normalMap: "/textures/portuguese/Portuguese_Tiles_006_normal.png",
    roughnessMap: "/textures/portuguese/Portuguese_Tiles_006_roughness.png",
    aoMap: "/textures/portuguese/Portuguese_Tiles_006_ambientOcclusion.png",
  });

  portugueseTextureProps.normalMap.repeat.set(1, 1);
  portugueseTextureProps.roughnessMap.repeat.set(1, 1);
  portugueseTextureProps.aoMap.repeat.set(1, 1);
  portugueseTextureProps.normalMap.wrapS = portugueseTextureProps.normalMap.wrapT = THREE.MirroredRepeatWrapping;
  portugueseTextureProps.roughnessMap.wrapS = portugueseTextureProps.roughnessMap.wrapT = THREE.MirroredRepeatWrapping;
  portugueseTextureProps.aoMap.wrapS = portugueseTextureProps.aoMap.wrapT = THREE.RepeatWrapping;


  return (
    <group {...props} dispose={null}>
      <group>
        <mesh name="polySurface11_polySurface12" geometry={nodes.polySurface11_polySurface12.geometry}>
          <meshStandardMaterial {...(material === "stylized" ? stylizedTextureProps : portugueseTextureProps)} />
        </mesh>
        <mesh name="polySurface11_polySurface12_1" geometry={nodes.polySurface11_polySurface12_1.geometry}>
          <meshStandardMaterial {...(material === "stylized" ? stylizedTextureProps : portugueseTextureProps)} />
        </mesh>
        <mesh name="polySurface13_polySurface14" geometry={nodes.polySurface13_polySurface14.geometry}>
          <meshStandardMaterial {...(material === "stylized" ? stylizedTextureProps : portugueseTextureProps)} />
        </mesh>
        <mesh name="polySurface13_polySurface14_1" geometry={nodes.polySurface13_polySurface14_1.geometry}>
          <meshStandardMaterial {...(material === "stylized" ? stylizedTextureProps : portugueseTextureProps)} />
        </mesh>
      </group>
    </group>
  )
}

useGLTF.preload('/models/guy.glb')
